name: Failure notifier
description: Comment on a PR when CI fails

inputs:
  github-token:
    description: GitHub token
    required: true

runs:
  using: "composite"
  steps:
    - name: Comment on PR
      if: ${{ github.event_name == 'pull_request' }}
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const author = context.payload.pull_request.user.login;
          const runUrl = `${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}`;
          const message = `🚨 Tests failed. @${author}, please review the results here: ${runUrl}`;

          await github.rest.issues.createComment({
            issue_number: context.payload.pull_request.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: message,
          });
