name: Run Forge Tests
on: [pull_request]

jobs:  
  bootstrap:
    name: Bootstrap environment
    runs-on: ubuntu-latest
    outputs:
      cache-path: ${{ steps.cache.outputs.path }}
      cache-key: ${{ steps.cache.outputs.key }}
    env:
      FORGE_REV: 03ea54c
    steps:
      - name: Build cache params
        id: cache
        run: |
          echo "path=$CACHE_PATH" >> "$GITHUB_OUTPUT"
          echo "$KEY_INPUT" | md5sum | awk '{print $1}' | xargs -I% echo "key=cargobin-%-${RUNNER_OS}" >> "$GITHUB_OUTPUT"
        env:
          CACHE_PATH: |
            ~/.cargo/bin/
          KEY_INPUT: |
            forge:${{env.FORGE_REV}}

      - uses: actions/cache@v4
        id: get-cache
        with:
          path: ${{ steps.cache.outputs.path }}
          key: ${{ steps.cache.outputs.key }}

      - name: Install forge & anvil
        run: cargo install --git https://github.com/foundry-rs/foundry --rev "$FORGE_REV" --profile release --locked forge anvil
        if: steps.get-cache.outputs.cache-hit != 'true'

  foundry:
    name: Foundry tests
    runs-on: ubuntu-latest
    needs: bootstrap
    env:
      FORGE_REV: 03ea54c
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/cache@v4
        with:
          path: ${{ needs.bootstrap.outputs.cache-path }}
          key: ${{ needs.bootstrap.outputs.cache-key }}

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: yarn
          cache-dependency-path: "**/yarn.lock"

      - name: Build
        run: forge build --sizes

      - name: Run local integration tests
        run: forge test
        env:
          MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}