name: Run Forge Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: yarn install --immutable

    - name: Install Foundry and Forge
      run: |
        curl -L https://foundry.paradigm.xyz | bash
        source ~/.bashrc
        foundryup

    - name: Run Forge tests
      env:
        MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
      run: |
        forge test --report report.json

    - name: Upload test report
      uses: actions/upload-artifact@v3
      with:
        name: forge-test-report
        path: report.json