name: Run Forge Tests
on: [push, pull_request]

jobs:
  foundry:
    name: Foundry tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: yarn
          cache-dependency-path: "**/yarn.lock"

      - name: Install dependencies
        run: forge install

      - name: Build
        run: forge build --sizes

      - name: Run unit-tests
        run: forge test
        env:
          MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}